// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJjxRZxZnb8T5EqEF_TcLw1lCOm6fOzMk',
    appId: '1:15274697382:web:6a7dba70584d2ce39b0a67',
    messagingSenderId: '15274697382',
    projectId: 'saloon-booking-app-78a8e',
    authDomain: 'saloon-booking-app-78a8e.firebaseapp.com',
    storageBucket: 'saloon-booking-app-78a8e.firebasestorage.app',
    measurementId: 'G-HSNLNMRR86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM2s9T4QLnKtcw0kAMrh-cFszSzT25cPw',
    appId: '1:15274697382:android:3c3f012956ae5bb39b0a67',
    messagingSenderId: '15274697382',
    projectId: 'saloon-booking-app-78a8e',
    storageBucket: 'saloon-booking-app-78a8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK5R4C9f5I79rIbpg2_5qpYZ71Z2wlM6I',
    appId: '1:15274697382:ios:25d0c4ceeda497849b0a67',
    messagingSenderId: '15274697382',
    projectId: 'saloon-booking-app-78a8e',
    storageBucket: 'saloon-booking-app-78a8e.firebasestorage.app',
    iosBundleId: 'com.example.saloonProject',
  );
}
